Const.V.update([3,6,4,75]);% 选取中等规模的固定环境变量

for i = 1:3
    SPT = Strategy.SPT(true);
    GA = Strategy.GA(true);
    LBGA = Strategy.LBGA(true);
    ALBGA = Strategy.ALBGA(true);

    g = 1:Const.F.MAX_GENERATION;

    res = [g', SPT, GA, LBGA, ALBGA];

    table = array2table(res, 'VariableNames', {...
        'Generation',...
        'SPT',...
        'GA_BF', 'GA_AF',...
        'LBGA_BF', 'LBGA_AF',...
        'ALBGA_BF', 'ALBGA_AF'
    });
    writetable(table, sprintf('result_%d.xlsx', i), 'WriteRowNames', true);

    figure;
    plot(res(:, 1), res(:, 2), ...
        res(:, 1), res(:, 3), '--',...
        res(:, 1), res(:, 4), ...
        res(:, 1), res(:, 5), '--',...
        res(:, 1), res(:, 6), ...
        res(:, 1), res(:, 7), '--',...
        res(:, 1), res(:, 8)  ...
    );
    title('GA (Genetic Algorithm)');
    xlabel('Generation');
    ylabel('1/Fitness');
    legend('SPT', 'GA(best)', 'GA(average)', 'LBGA(best)', 'LBGA(average)', 'ALBGA(best)', 'ALBGA(average)');
    saveas(gcf, sprintf('result_%d.png', i));
end